name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_font_icons: ^2.2.7
  webview_flutter: ^4.0.0
  geolocator: ^13.0.3
  geolocator_android: ^4.6.2
  geolocator_web: ^4.1.2
  geolocator_windows: ^0.2.4
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  intl: ^0.18.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  google_fonts: ^6.2.1
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icoApk.png" # Ruta al ícono que deseas usar

flutter:
  uses-material-design: true

  assets:
    - assets/images/w3.jpg